### ISSUE TITLE
Plugin compiles, but can't be used

### ISSUE THREAD

**Issue by brinza888** [DevGonzi/uMod-Build#1]
In some internal reasons this plugin couldn't be loaded by my server. These errors I ve found in my oxide log:

```
01:04 [Error] Could not load plugin 'Build' (no plugin found with that file name)
01:05 [Error] Error while compiling: Build.cs(341,52): error CS0176: Static member `FileSystemBackend.cache' cannot be accessed with an instance reference, qualify it with a type name instead
01:06 [Error] Error while compiling: Build.cs(341,52): error CS0176: Static member `FileSystemBackend.cache' cannot be accessed with an instance reference, qualify it with a type name instead
```

**Comment by Spiikesan** [comment]
Hi, download the version 2.2.2 from there to fix that issue: https://umod.org/plugins/build

**Comment by nsomneeak** [comment]
> Hi, download the version 2.2.2 from there to fix that issue: https://umod.org/plugins/build

I received the same error with 2.2.2 and the code directly from here. I resolved the error by changing line 339 from `foreach (var str in FileSystemBackend.Backend.cache.Keys)` to `foreach (var str in FileSystemBackend.cache.Keys)`

**Comment by Spiikesan** [comment]
If FileSystemBackend works, then your Oxide installation is out of date.

**Comment by brinza888** [comment]
Yes, you are correct, Oxide have been updated few days ago, I just have previous release. In changelog I found something about FileSystemBackend. So this seems like solution.
![image](https://user-images.githubusercontent.com/29017599/179025559-ea63bc34-df89-4404-924d-0708d04a766c.png)
